# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1320, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(400, 400))
        mainWindow.setBaseSize(QtCore.QSize(1200, 700))
        self.centralWidget = QtWidgets.QWidget(mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 170, 1300, 471))
        self.textBrowser.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.textBrowser.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1301, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_2.setMaximumSize(QtCore.QSize(280, 16777215))
        self.comboBox_2.setStyleSheet("background: rgb(150, 220, 220)")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_made = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_made.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox_made.setText("")
        self.checkBox_made.setChecked(True)
        self.checkBox_made.setObjectName("checkBox_made")
        self.horizontalLayout_9.addWidget(self.checkBox_made)
        self.lineEdit_made = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_made.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_made.setAutoFillBackground(False)
        self.lineEdit_made.setStyleSheet(" background: rgb(150, 220, 220)")
        self.lineEdit_made.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_made.setObjectName("lineEdit_made")
        self.horizontalLayout_9.addWidget(self.lineEdit_made)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_model = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_model.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox_model.setText("")
        self.checkBox_model.setChecked(True)
        self.checkBox_model.setObjectName("checkBox_model")
        self.horizontalLayout_10.addWidget(self.checkBox_model)
        self.lineEdit_model = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_model.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_model.setAutoFillBackground(False)
        self.lineEdit_model.setStyleSheet(" background: rgb(150, 220, 220)")
        self.lineEdit_model.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_model.setObjectName("lineEdit_model")
        self.horizontalLayout_10.addWidget(self.lineEdit_model)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_10)
        self.lineEdit_ser_num = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ser_num.sizePolicy().hasHeightForWidth())
        self.lineEdit_ser_num.setSizePolicy(sizePolicy)
        self.lineEdit_ser_num.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_ser_num.setMaximumSize(QtCore.QSize(350, 16777215))
        self.lineEdit_ser_num.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.lineEdit_ser_num.setText("")
        self.lineEdit_ser_num.setMaxLength(10)
        self.lineEdit_ser_num.setObjectName("lineEdit_ser_num")
        self.horizontalLayout_2.addWidget(self.lineEdit_ser_num)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_room = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.lineEdit_room.sizePolicy().hasHeightForWidth())
        self.lineEdit_room.setSizePolicy(sizePolicy)
        self.lineEdit_room.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_room.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_room.setMaxLength(6)
        self.lineEdit_room.setObjectName("lineEdit_room")
        self.horizontalLayout.addWidget(self.lineEdit_room)
        self.lineEdit_human = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.lineEdit_human.sizePolicy().hasHeightForWidth())
        self.lineEdit_human.setSizePolicy(sizePolicy)
        self.lineEdit_human.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_human.setInputMethodHints(QtCore.Qt.ImhDate)
        self.lineEdit_human.setObjectName("lineEdit_human")
        self.horizontalLayout.addWidget(self.lineEdit_human)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_data_pay = QtWidgets.QLabel(self.layoutWidget)
        self.label_data_pay.setObjectName("label_data_pay")
        self.horizontalLayout_5.addWidget(self.label_data_pay)
        self.dateEdit_data_pay = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_data_pay.setMinimumSize(QtCore.QSize(100, 26))
        self.dateEdit_data_pay.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 12, 19), QtCore.QTime(0, 0, 0)))
        self.dateEdit_data_pay.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 12, 19), QtCore.QTime(0, 0, 0)))
        self.dateEdit_data_pay.setMinimumDate(QtCore.QDate(2000, 12, 19))
        self.dateEdit_data_pay.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_data_pay.setCalendarPopup(True)
        self.dateEdit_data_pay.setObjectName("dateEdit_data_pay")
        self.horizontalLayout_5.addWidget(self.dateEdit_data_pay)
        self.horizontalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_lifetime = QtWidgets.QLabel(self.layoutWidget)
        self.label_lifetime.setObjectName("label_lifetime")
        self.horizontalLayout_7.addWidget(self.label_lifetime)
        self.spinBox_lifetime = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_lifetime.setMinimumSize(QtCore.QSize(20, 25))
        self.spinBox_lifetime.setObjectName("spinBox_lifetime")
        self.horizontalLayout_7.addWidget(self.spinBox_lifetime)
        self.horizontalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_data_amort = QtWidgets.QLabel(self.layoutWidget)
        self.label_data_amort.setObjectName("label_data_amort")
        self.horizontalLayout_6.addWidget(self.label_data_amort)
        self.lineEdit_data_amort = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_amort.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_amort.setSizePolicy(sizePolicy)
        self.lineEdit_data_amort.setMinimumSize(QtCore.QSize(100, 25))
        self.lineEdit_data_amort.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_data_amort.setInputMask("")
        self.lineEdit_data_amort.setMaxLength(32767)
        self.lineEdit_data_amort.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_data_amort.setReadOnly(True)
        self.lineEdit_data_amort.setObjectName("lineEdit_data_amort")
        self.horizontalLayout_6.addWidget(self.lineEdit_data_amort)
        self.horizontalLayout.addLayout(self.horizontalLayout_6)
        self.pushButton_append = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_append.sizePolicy().hasHeightForWidth())
        self.pushButton_append.setSizePolicy(sizePolicy)
        self.pushButton_append.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_append.setFont(font)
        self.pushButton_append.setStyleSheet("background-color: rgb(239, 150,150);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_append.setFlat(False)
        self.pushButton_append.setObjectName("pushButton_append")
        self.horizontalLayout.addWidget(self.pushButton_append)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox.setStyleSheet("background: rgb(150, 220, 220)")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.lineEdit_data_rem = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_data_rem.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lineEdit_data_rem.setObjectName("lineEdit_data_rem")
        self.horizontalLayout_3.addWidget(self.lineEdit_data_rem)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_3.addLayout(self.horizontalLayout_11)
        self.lineEdit_error = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_error.setEnabled(True)
        self.lineEdit_error.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_error.setObjectName("lineEdit_error")
        self.horizontalLayout_3.addWidget(self.lineEdit_error)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_phone = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_phone.sizePolicy().hasHeightForWidth())
        self.lineEdit_phone.setSizePolicy(sizePolicy)
        self.lineEdit_phone.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_phone.setMaxLength(14)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.horizontalLayout_4.addWidget(self.lineEdit_phone)
        spacerItem = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_full = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_full.sizePolicy().hasHeightForWidth())
        self.radioButton_full.setSizePolicy(sizePolicy)
        self.radioButton_full.setObjectName("radioButton_full")
        self.horizontalLayout_8.addWidget(self.radioButton_full)
        self.radioButton_amort = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_amort.sizePolicy().hasHeightForWidth())
        self.radioButton_amort.setSizePolicy(sizePolicy)
        self.radioButton_amort.setObjectName("radioButton_amort")
        self.horizontalLayout_8.addWidget(self.radioButton_amort)
        self.radioButton_state = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_state.sizePolicy().hasHeightForWidth())
        self.radioButton_state.setSizePolicy(sizePolicy)
        self.radioButton_state.setObjectName("radioButton_state")
        self.horizontalLayout_8.addWidget(self.radioButton_state)
        self.radioButton_hr = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_hr.sizePolicy().hasHeightForWidth())
        self.radioButton_hr.setSizePolicy(sizePolicy)
        self.radioButton_hr.setObjectName("radioButton_hr")
        self.horizontalLayout_8.addWidget(self.radioButton_hr)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(250, 17, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_remove = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.pushButton_remove.sizePolicy().hasHeightForWidth())
        self.pushButton_remove.setSizePolicy(sizePolicy)
        self.pushButton_remove.setMinimumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_remove.setFont(font)
        self.pushButton_remove.setStyleSheet("background-color: rgb(239, 150,150);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.horizontalLayout_4.addWidget(self.pushButton_remove)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        mainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1320, 22))
        self.menuBar.setObjectName("menuBar")
        mainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(mainWindow)
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "База.Принтеры"))
        self.textBrowser.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\';\"><br /></p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("mainWindow", "Все типы"))
        self.comboBox_2.setItemText(1, _translate("mainWindow", "Лазерный ч/б"))
        self.comboBox_2.setItemText(2, _translate("mainWindow", "Лазерный цветной"))
        self.comboBox_2.setItemText(3, _translate("mainWindow", "Струйный"))
        self.lineEdit_made.setPlaceholderText(_translate("mainWindow", "Производитель..."))
        self.lineEdit_model.setPlaceholderText(_translate("mainWindow", "Модель..."))
        self.lineEdit_ser_num.setPlaceholderText(_translate("mainWindow", "Инвентарный №..."))
        self.lineEdit_room.setPlaceholderText(_translate("mainWindow", "Кабинет №..."))
        self.lineEdit_human.setPlaceholderText(_translate("mainWindow", "Сотрудник..."))
        self.label_data_pay.setText(_translate("mainWindow", "Дата покупки"))
        self.dateEdit_data_pay.setDisplayFormat(_translate("mainWindow", "dd.MM.yyyy"))
        self.label_lifetime.setText(_translate("mainWindow", "Срок амортизации"))
        self.label_data_amort.setText(_translate("mainWindow", "Окончание амортизации"))
        self.lineEdit_data_amort.setPlaceholderText(_translate("mainWindow", "..."))
        self.pushButton_append.setText(_translate("mainWindow", "+"))
        self.comboBox.setItemText(0, _translate("mainWindow", "все состояния"))
        self.comboBox.setItemText(1, _translate("mainWindow", "исправен"))
        self.comboBox.setItemText(2, _translate("mainWindow", "в ремонте"))
        self.lineEdit_data_rem.setPlaceholderText(_translate("mainWindow", "Дата поступления в ремонт..."))
        self.lineEdit_error.setPlaceholderText(_translate("mainWindow", "Неисправность..."))
        self.lineEdit_phone.setPlaceholderText(_translate("mainWindow", "Телефон..."))
        self.radioButton_full.setText(_translate("mainWindow", "Полная форма"))
        self.radioButton_amort.setText(_translate("mainWindow", "Амортизация"))
        self.radioButton_state.setText(_translate("mainWindow", "Состояние"))
        self.radioButton_hr.setText(_translate("mainWindow", "Персонал"))
        self.pushButton_remove.setText(_translate("mainWindow", "-"))
